DATALOADER:
  NUM_WORKERS: 8
  TRAIN_X:
    BATCH_SIZE: 128
    SAMPLER: "RandomDomainSampler" # to use m3sda

  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 128
  
    # to do multi domain,otherwise close
    SAMPLER: "SeqDomainSampler"

  TEST:
    BATCH_SIZE: 128  
    # to do mixmatch,otherwise close
  K_TRANSFORMS: 3
  
OPTIM:
  NAME: "sgd"
  LR: 0.005
  MAX_EPOCH: 3000
  LR_SCHEDULER: "cosine"

#TRAIN:
 # COUNT_ITER: "train_u"
 # PRINT_FREQ: 10

TRAINER:
  FIXMATCH:
    STRONG_TRANSFORMS: ["random_flip", "randaugment_fixmatch", "normalize", "cutout"]
