DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
    SAMPLER: RandomDomainSampler # to do m3sda

  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 32
  
    # to do multi domain,otherwise close
    SAMPLER: SeqDomainSampler

  TEST:
    BATCH_SIZE: 32  
    # to do mixmatch,otherwise close
  K_TRANSFORMS: 3
  
OPTIM:
  NAME: "sgd"
  LR: 0.05
  # LR: 3e-4
  STEPSIZE: [30]
  MAX_EPOCH: 3000
  LR_SCHEDULER: "cosine"

#TRAIN:
 # COUNT_ITER: "train_u"
 # PRINT_FREQ: 10

TRAINER:
  FIXMATCH:
    STRONG_TRANSFORMS: ["random_flip", "randaugment_fixmatch", "normalize", "cutout"]
