INPUT:
  SIZE: (32, 32)
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  TRANSFORMS: ["random_crop","normalize"]

DATASET:
  NAME: "Digit5"
  NUM_LABELED: 50
  VAL_PERCENT: 0.


MODEL:
  BACKBONE:
   # NAME: "cnn_digit5_m3sda"
    NAME: "wide_resnet_28_2"
