INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "random_translation", "normalize"]

DATASET:
  NAME: "DomainNet"
  NUM_LABELED: 10 # every class number
  VAL_PERCENT: 0.

MODEL:
  BACKBONE:
    NAME: "resnet101"
