INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_crop", "random_translation","normalize"]

DATASET:
  NAME: "OfficeHome"
  NUM_LABELED: 10 # class number

MODEL:
  BACKBONE:
    NAME: "resnet18"
    PRETRAINED: True
